# Add the contents of this file to `config.toml` to enable "fast build" configuration. Please read the notes below.
# NOTE: For maximum performance, build using a nightly compiler
# If you are using rust stable, remove the "-Zshare-generics=y" below.


[build]
# number of parallel jobs, defaults to # of CPUs
jobs = 8  
# whether or not to enable incremental compilation
incremental = true           
rustflags = ["-C","split-debuginfo=unpacked","--cfg","getrandom_backend=\"wasm_js\""]

[env]
RUST_BACKTRACE = "full" 
RUST_LOG = "info"

[profile.dev]
# Optional: Uncommenting the following improves compile times, but reduces the amount of debug info to 'line number tables only'
# In most cases the gains are negligible, but if you are on macos and have slow compile times you should see significant gains.
debug = 2
incremental = true
#split-debuginfo = "unpacked" # faster debug builds on mac
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
incremental = true
# opt-level = 's' # 10-20% smaller wasm compared to `opt-level = 3`
# opt-level = 1 # very slow and big wasm. Don't do this.
opt-level = 2 # fast and small wasm, basically same as `opt-level = 's'`
# opt-level = 3 # unecessarily large wasm for no performance gain

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Oz']

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

# NOTE: you must manually install https://github.com/michaeleisel/zld on mac. you can easily do this with the "brew" package manager:
# `brew install michaeleisel/zld/zld`
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld"]

[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis --cfg getrandom_backend=\"wasm_js\""]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

